### ISSUE TITLE
Bundler could not find compatible versions for gem "deface"

### ISSUE THREAD

**Issue by Sir-Will** [AlphaNodes/redmine_messenger#102]
Hey,

I tried updating the plugin from 1.0.7 to 1.0.13 with Redmine version 4.2.1.stable, but I'm getting the following error:

```
Bundler could not find compatible versions for gem "deface":
  In Gemfile:
    deface (= 1.5.3)

    redmine_plugin_kit was resolved to 1.0.1, which depends on
      deface (= 1.8.1)
```

**Comment by alexandermeindl** [comment]
Remove deface from your Gemfile.local or remove other plugins, which require deface 1.5.3. Then it should work 😉

**Comment by Sir-Will** [comment]
Ah, thank you.

Now I'm getting this error:
```
Migrating plugins. Please be patient, this could take a while...
rake aborted!
LoadError: Unable to autoload constant RedmineMessenger::Hooks, expected /home/redmine/redmine/plugins/redmine_messenger/lib/redmine_messenger/hooks.rb to define it
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:511:in `load_missing_constant'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:195:in `const_missing'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/redmine_plugin_kit-1.0.3/lib/redmine_plugin_kit/loader.rb:107:in `load_model_hooks!'
/home/redmine/redmine/plugins/redmine_messenger/init.rb:20:in `block in <top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/redmine_plugin_kit-1.0.3/lib/redmine_plugin_kit/loader.rb:22:in `persisting'
/home/redmine/redmine/plugins/redmine_messenger/init.rb:20:in `<top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/redmine/lib/redmine/plugin.rb:187:in `block in load'
/home/redmine/redmine/lib/redmine/plugin.rb:178:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:178:in `load'
/home/redmine/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:285:in `load'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:285:in `block in load'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:285:in `load'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/engine.rb:663:in `block in load_config_initializer'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:170:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/engine.rb:662:in `load_config_initializer'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/engine.rb:619:in `each'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/engine.rb:619:in `block in <class:Engine>'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `instance_exec'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/initializable.rb:32:in `run'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/initializable.rb:50:in `each'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/initializable.rb:60:in `run_initializers'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/application.rb:361:in `initialize!'
/home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/application.rb:337:in `require_environment!'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/redmine/data/tmp/bundle/ruby/2.6.0/gems/rake-13.0.4/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by Sir-Will** [comment]
Nvm, deleting the tmp folder resolved it.
