### ISSUE TITLE
Cannot work with fixing keywords.

### ISSUE THREAD

**Issue by wangyh-c** [alphanodes/redmine_messenger#76]
Hi dude.  
I'm very enjoy this plugin, but there is a problem make me sad.  
purpose is to updating the issue percentage when I push my code with some commit message like this "[FIX] module: balbalabal . { done20 #117 @1h}"
but when I just change the issue status in website, the plugin works well.

I set my fixing keyword like below picture, 
![图片](https://user-images.githubusercontent.com/47807894/92111090-5aeafa80-ee1e-11ea-845a-2ef177834d2a.png)  

This picture is how i config the plugin:  
![图片](https://user-images.githubusercontent.com/47807894/92111209-8e2d8980-ee1e-11ea-8838-0cb7fe42f65a.png)  

And the last picture is the system log:  
![图片](https://user-images.githubusercontent.com/47807894/92111550-098f3b00-ee1f-11ea-9980-b9bdf061c0a5.png)

**Comment by alreadytakenn** [comment]
BTY, I have checked the  format of keyword in my commit message, it's no problem. and thanks in advance.

**Comment by mehmetalianil** [comment]
This is still a relevant bug, why was this closed?

**Comment by mehmetalianil** [comment]
I mean, I stumbled on it, ref https://www.redmine.org/issues/34575

**Comment by alexandermeindl** [comment]
Hi @mehmetalianil 
Can you provide more information (log?) for your error? I cannot reproduce it. Do you use the latest version of redmine_messenger (master branch)?

**Comment by alexandermeindl** [comment]
Hi again, I think, your problem was fixed by https://github.com/AlphaNodes/redmine_messenger/pull/85

Let me know, if your problem exists with the latest master version.

**Comment by mehmetalianil** [comment]
I there, I was using 1.0.8-master, with Redmine 4.1.1
Confidently I made a Loom recording for this, but I wasn't actually able to reproduce the issue either. I guess the actual bug requires a more elaborate chain of events for me. 
https://www.loom.com/share/e5a3288403a14172bb96c1a22b1565c7

**Comment by alexandermeindl** [comment]
Make sure, you have the latest updates from master branch. There is not a new version created for the latest changes. I am quite sure, that https://github.com/AlphaNodes/redmine_messenger/commit/67a8faa284fcb655645450bee13a633eae4212cd fixed your problem.

**Comment by mehmetalianil** [comment]
I couldn't reproduce it either, but when I encountered it, this was the traceback:
```
I, [2021-06-17T10:51:52.612905 #57786]  INFO -- : Completed 500 Internal Server Error in 247ms (ActiveRecord: 44.8ms)                                                                                             │F, [2021-06-17T10:51:52.613820 #57786] FATAL -- :                                                                                                                                                                 │F, [2021-06-17T10:51:52.613873 #57786] FATAL -- : RuntimeError (string modified):                                                                                                                                 │F, [2021-06-17T10:51:52.613903 #57786] FATAL -- :                                                                                                                                                                 │F, [2021-06-17T10:51:52.613933 #57786] FATAL -- : app/models/changeset.rb:130:in `scan'                                                                                                                           │app/models/changeset.rb:130:in `scan_comment_for_issue_ids'                                                                                                                                                       │app/models/changeset.rb:103:in `scan_for_issues'                                                                                                                                                                  │app/models/repository/git.rb:221:in `save_revision'                                                                                                                                                               │
app/models/repository/git.rb:210:in `block (2 levels) in save_revisions'                                                                                                                                          │
app/models/repository/git.rb:207:in `block in save_revisions'                                                                                                                                                     │
app/models/repository/git.rb:206:in `each'                                                                                                                                                                        │
app/models/repository/git.rb:206:in `save_revisions'                                                                                                                                                              │
app/models/repository/git.rb:156:in `fetch_changesets'                                                                                                                                                            │
app/controllers/repositories_controller.rb:86:in `show'                                                                                                                                                           │
plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:27:in `show'                                                                                                         │
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```
This could also be cause by the redmine-git-hosting plugin, which I guess @alreadytakenn also had.



> Make sure, you have the latest updates from master branch. There is not a new version created for the latest changes. I am quite sure, that [67a8faa](https://github.com/AlphaNodes/redmine_messenger/commit/67a8faa284fcb655645450bee13a633eae4212cd) fixed your problem.

I did not know about that, I will update shortly. Thanks.
